@ParametersAreNonnullByDefault @MethodsReturnNonnullByDefault
package mrp_v2.additionalcolors.api.colored_block_data;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;