@ParametersAreNonnullByDefault @MethodsReturnNonnullByDefault
package mrp_v2.additionalcolors.api.datagen;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;