@ParametersAreNonnullByDefault @MethodsReturnNonnullByDefault
package mrp_v2.additionalcolors.datagen;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;