@ParametersAreNonnullByDefault @MethodsReturnNonnullByDefault
package mrp_v2.additionalcolors.client.particle;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;